language: node_js
node_js:
- '8'
install:
- yarn install
before_script:
- yarn run build
script:
- yarn run test
after_success:
- yarn run deploy
deploy:
  provider: npm
  email: andrewmclagan@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: L25lfiPN/IagXM2zZA5/8de10oubFvtlvCn0TVJbJ0UQtsvfKyEqImKGB62ZF90ZUUx5E5576PkRK8keT5ACQVSW3TDOPPQOxpmmMpOrY6Yg/HekLmFo11JT/8w4hsVVZHQAy/eedftRhZCTbLyODU26wtBSkWtzX4vHg350d9pSTpgs6M0BL3qcivpVoQ4TDX2HUPOJMO7rkcxhgXYNgl/lZgMP6nUiHwfxec9sO7VwXbGFUKqWBYpwK6mnXc1RtGjYuTGzYDFFUqdOeBf/t3jySCNYFx8HpPg7iG13aKxGiRGtjscdXOnAAPd379Ecm7SiqOtEqzVVqDLJdsj/mkK8xge7BLmU7Aw3B2AnfFOQia87MCUUqxyWUIOEj+sv/j/vbYUTpydOLyMkRadjl3CNIsMIw6m47zAxa5fq6ZdsCE1HsfynzhYWslk83tG+TpkQKGIzMBqlzWclLOiigFsdwPBMQhiHkAGkBC39PtALXzBS1LH6pIkntECkfWQ+7I64aYf7dvFPDgAYABvEG7WSk+9mxOlO/00r1lqHwus9xJ9iP50A2C/QwnZuHJqQjrmiicKvadPagoSAoVV1vXsfmg3rLcIAG6z4Qy1usKFVNWxRjQfLtzIarn9zCKFSp0YFLuprZLkBS5V77zhv0OeGmIEXL2jpU1GYHyX0JVQ=
cache: yarn
